import type {
  Company,
  DashboardStats,
  Signal,
  Workflow,
  Conversation,
  Buyer,
  BuyerOutreachData,
} from '@/types'

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  total_companies: 1247,
  high_intent_companies: 342,
  medium_intent_companies: 568,
  low_intent_companies: 337,
  intent_distribution: [
    { name: 'High Intent', value: 342, color: '#10b981' },
    { name: 'Medium Intent', value: 568, color: '#f59e0b' },
    { name: 'Low Intent', value: 337, color: '#ef4444' },
  ],
  channel_effectiveness: [
    { channel: 'LinkedIn', effectiveness: 85, count: 450 },
    { channel: 'Email', effectiveness: 72, count: 520 },
    { channel: 'WhatsApp', effectiveness: 68, count: 277 },
  ],
  success_rate_trend: [
    { date: '2026-01-01', rate: 65 },
    { date: '2026-01-08', rate: 68 },
    { date: '2026-01-15', rate: 71 },
    { date: '2026-01-22', rate: 73 },
    { date: '2026-01-29', rate: 75 },
    { date: '2026-02-05', rate: 78 },
    { date: '2026-02-12', rate: 80 },
    { date: '2026-02-19', rate: 82 },
  ],
  recent_companies: [
    {
      id: '1',
      name: 'Tesla Inc.',
      industry: 'Automotive',
      location: 'Austin, TX',
      intent_score: 92,
      hiring_signal: 'Hiring 15 AI Engineers',
      engagement_score: 88,
      recommended_channel: 'LinkedIn',
      confidence_score: 94,
      status: 'Active',
      last_signal: '2 hours ago',
    },
    {
      id: '2',
      name: 'Microsoft',
      industry: 'Technology',
      location: 'Redmond, WA',
      intent_score: 87,
      hiring_signal: 'Opened new AI lab',
      engagement_score: 85,
      recommended_channel: 'Email',
      confidence_score: 91,
      status: 'Active',
      last_signal: '5 hours ago',
    },
    {
      id: '3',
      name: 'Stripe',
      industry: 'FinTech',
      location: 'San Francisco, CA',
      intent_score: 78,
      hiring_signal: 'Hiring Backend Engineers',
      engagement_score: 76,
      recommended_channel: 'LinkedIn',
      confidence_score: 82,
      status: 'Active',
      last_signal: '1 day ago',
    },
  ],
  upcoming_meetings: [
    {
      id: 'm1',
      company_name: 'Tesla Inc.',
      contact_name: 'John Doe',
      time: '2026-02-22T10:00:00Z',
      duration: '45 min',
      type: 'Video',
      status: 'Confirmed',
    },
    {
      id: 'm2',
      company_name: 'Stripe',
      contact_name: 'Sarah Smith',
      time: '2026-02-22T14:30:00Z',
      duration: '30 min',
      type: 'Call',
      status: 'Confirmed',
    },
    {
      id: 'm3',
      company_name: 'Microsoft',
      contact_name: 'Michael Brown',
      time: '2026-02-23T09:00:00Z',
      duration: '60 min',
      type: 'Video',
      status: 'Pending',
    },
  ],
}

// Mock Companies
export const mockCompaniesList: Company[] = [
  {
    id: '1',
    name: 'Tesla Inc.',
    industry: 'Automotive',
    location: 'Austin, TX',
    intent_score: 92,
    hiring_signal: 'Hiring 15 AI Engineers',
    engagement_score: 88,
    recommended_channel: 'LinkedIn',
    confidence_score: 94,
    status: 'Active',
    last_signal: '2 hours ago',
  },
  {
    id: '2',
    name: 'Microsoft',
    industry: 'Technology',
    location: 'Redmond, WA',
    intent_score: 87,
    hiring_signal: 'Opened new AI lab',
    engagement_score: 85,
    recommended_channel: 'Email',
    confidence_score: 91,
    status: 'Active',
    last_signal: '5 hours ago',
  },
  {
    id: '3',
    name: 'Stripe',
    industry: 'FinTech',
    location: 'San Francisco, CA',
    intent_score: 78,
    hiring_signal: 'Hiring Backend Engineers',
    engagement_score: 76,
    recommended_channel: 'LinkedIn',
    confidence_score: 82,
    status: 'Active',
    last_signal: '1 day ago',
  },
  {
    id: '4',
    name: 'Airbnb',
    industry: 'Travel',
    location: 'San Francisco, CA',
    intent_score: 74,
    hiring_signal: 'Expanding team',
    engagement_score: 72,
    recommended_channel: 'Email',
    confidence_score: 78,
    status: 'Active',
    last_signal: '2 days ago',
  },
  {
    id: '5',
    name: 'Uber',
    industry: 'Transportation',
    location: 'San Francisco, CA',
    intent_score: 69,
    hiring_signal: 'Hiring Product Managers',
    engagement_score: 65,
    recommended_channel: 'LinkedIn',
    confidence_score: 73,
    status: 'Active',
    last_signal: '3 days ago',
  },
]

// Mock Company Detail
export const mockCompanyDetail: Company = {
  id: '1',
  name: 'Tesla Inc.',
  industry: 'Automotive',
  location: 'Austin, TX',
  intent_score: 92,
  hiring_signal: 'Hiring 15 AI Engineers',
  engagement_score: 88,
  recommended_channel: 'LinkedIn',
  confidence_score: 94,
  status: 'Active',
  signals: [
    {
      id: 's1',
      type: 'hiring',
      title: 'Hiring 15 AI Engineers',
      description: 'Tesla is actively hiring AI engineers for their autopilot team',
      strength: 95,
      timestamp: '2026-02-21T10:00:00Z',
      source: 'LinkedIn Jobs',
    },
    {
      id: 's2',
      type: 'linkedin',
      title: 'High engagement on AI posts',
      description: 'Company executives showing strong interest in AI content',
      strength: 88,
      timestamp: '2026-02-20T15:30:00Z',
      source: 'LinkedIn Activity',
    },
    {
      id: 's3',
      type: 'news',
      title: 'Announced new AI research initiative',
      description: 'Tesla announced $100M investment in AI research',
      strength: 92,
      timestamp: '2026-02-19T09:00:00Z',
      source: 'TechCrunch',
    },
  ],
  strategy: {
    id: 'str1',
    company_id: '1',
    recommended_channel: 'LinkedIn',
    recommended_timing: 'Tuesday or Wednesday, 9-11 AM',
    recommended_tone: 'Professional, technical, data-driven',
    strategy_explanation:
      'Based on hiring signals and LinkedIn engagement, a direct approach highlighting AI expertise and technical capabilities would be most effective. Focus on concrete achievements and data.',
    confidence_score: 94,
    signal_contributions: [
      { signal_type: 'Hiring Signals', contribution_percentage: 45 },
      { signal_type: 'LinkedIn Activity', contribution_percentage: 30 },
      { signal_type: 'News & Events', contribution_percentage: 25 },
    ],
  },
  content: {
    linkedin_message: "Hi [Name],\n\nI noticed Tesla is expanding its AI engineering team. With our expertise in scalable machine learning infrastructure and autonomous systems, I believe we could add significant value to your autopilot initiatives.\n\nWe've helped similar automotive companies reduce model training time by 60% and improve accuracy by 15%. Would you be open to a brief conversation about your AI infrastructure needs?\n\nBest regards",
    email_message: "Subject: AI Infrastructure Solutions for Tesla's Autopilot Team\n\nDear [Name],\n\nI hope this email finds you well. I'm reaching out because I noticed Tesla's recent announcement about expanding the AI engineering team and investing $100M in AI research.\n\nAt [Your Company], we specialize in building scalable AI infrastructure for autonomous systems. We've recently helped automotive companies:\n- Reduce model training time by 60%\n- Improve inference latency by 40%\n- Scale to process 10M+ data points daily\n\nGiven Tesla's ambitious AI goals, I'd love to explore how we could support your initiatives. Would you be available for a 15-minute call next week?\n\nBest regards,\n[Your Name]",
    whatsapp_message: "Hi [Name] 👋\n\nI saw Tesla is hiring AI engineers! We've built ML infrastructure for autonomous vehicles that cut training time by 60%.\n\nQuick question: Are you open to exploring AI infrastructure solutions? Happy to share some case studies.\n\n[Your Name]",
  },
}

// Mock Signals
export const mockSignals: Signal[] = [
  {
    id: 's1',
    type: 'hiring',
    title: 'Tesla hiring 15 AI Engineers',
    description: 'Tesla is actively recruiting for autopilot team expansion',
    strength: 95,
    timestamp: '2026-02-21T10:00:00Z',
    source: 'LinkedIn Jobs',
  },
  {
    id: 's2',
    type: 'news',
    title: 'Microsoft opened new AI research lab',
    description: 'Microsoft announced a new $50M AI research facility in Seattle',
    strength: 90,
    timestamp: '2026-02-21T08:30:00Z',
    source: 'TechCrunch',
  },
  {
    id: 's3',
    type: 'hiring',
    title: 'Stripe hiring Backend Engineers',
    description: 'Stripe expanding payments infrastructure team',
    strength: 85,
    timestamp: '2026-02-20T16:45:00Z',
    source: 'LinkedIn Jobs',
  },
  {
    id: 's4',
    type: 'linkedin',
    title: 'Airbnb executives engaging with SaaS content',
    description: 'Multiple C-level executives showing interest in enterprise SaaS',
    strength: 78,
    timestamp: '2026-02-20T14:20:00Z',
    source: 'LinkedIn Activity',
  },
]

// Mock Workflow
export const mockWorkflow: Workflow = {
  id: 'wf1',
  company_id: '1',
  status: 'active',
  nodes: [
    {
      id: '1',
      type: 'start',
      label: 'Start',
      status: 'completed',
      position: { x: 250, y: 50 },
      data: { label: 'Start Workflow' },
    },
    {
      id: '2',
      type: 'action',
      label: 'Visit Profile',
      status: 'completed',
      position: { x: 250, y: 150 },
      data: { label: 'Visit LinkedIn Profile', timing: 'Day 1' },
    },
    {
      id: '3',
      type: 'action',
      label: 'Send Connection',
      status: 'completed',
      position: { x: 250, y: 250 },
      data: { label: 'Send Connection Request', timing: 'Day 1' },
    },
    {
      id: '4',
      type: 'decision',
      label: 'Accepted?',
      status: 'active',
      position: { x: 250, y: 350 },
      data: { label: 'Connection Accepted?' },
    },
    {
      id: '5',
      type: 'action',
      label: 'Send Message',
      status: 'pending',
      position: { x: 100, y: 450 },
      data: { label: 'Send LinkedIn Message', timing: 'Day 3' },
    },
    {
      id: '6',
      type: 'action',
      label: 'Send Email',
      status: 'pending',
      position: { x: 400, y: 450 },
      data: { label: 'Send Cold Email', timing: 'Day 2' },
    },
    {
      id: '7',
      type: 'action',
      label: 'Follow Up',
      status: 'pending',
      position: { x: 250, y: 550 },
      data: { label: 'Follow Up Message', timing: 'Day 7' },
    },
    {
      id: '8',
      type: 'end',
      label: 'End',
      status: 'pending',
      position: { x: 250, y: 650 },
      data: { label: 'Complete Workflow' },
    },
  ],
  edges: [
    { id: 'e1-2', source: '1', target: '2' },
    { id: 'e2-3', source: '2', target: '3' },
    { id: 'e3-4', source: '3', target: '4' },
    { id: 'e4-5', source: '4', target: '5', animated: true },
    { id: 'e4-6', source: '4', target: '6' },
    { id: 'e5-7', source: '5', target: '7' },
    { id: 'e6-7', source: '6', target: '7' },
    { id: 'e7-8', source: '7', target: '8' },
  ],
}

// Mock Conversations
export const mockConversations: Conversation[] = [
  {
    id: 'c1',
    company_name: 'Tesla Inc.',
    company_id: '1',
    last_message: 'That sounds great! Let me check with my team.',
    last_message_time: '2026-02-21T11:30:00Z',
    unread_count: 2,
    messages: [
      {
        id: 'm1',
        sender: 'user',
        content: "Hi! I noticed you're hiring AI engineers. Would love to discuss how we can help.",
        timestamp: '2026-02-21T10:00:00Z',
        status: 'read',
      },
      {
        id: 'm2',
        sender: 'contact',
        content: "Thanks for reaching out! Yes, we're expanding our team. What solutions do you offer?",
        timestamp: '2026-02-21T10:15:00Z',
      },
      {
        id: 'm3',
        sender: 'user',
        content: 'We provide ML infrastructure that can reduce training time by 60%. Can we schedule a demo?',
        timestamp: '2026-02-21T10:30:00Z',
        status: 'read',
      },
      {
        id: 'm4',
        sender: 'contact',
        content: 'That sounds great! Let me check with my team.',
        timestamp: '2026-02-21T11:30:00Z',
      },
    ],
  },
  {
    id: 'c2',
    company_name: 'Microsoft',
    company_id: '2',
    last_message: 'Sounds great! Let me coordinate with the Azure team.',
    last_message_time: '2026-02-20T16:45:00Z',
    unread_count: 3,
    messages: [
      {
        id: 'm5',
        sender: 'user',
        content: "Hi! Congratulations on the new AI research lab in Seattle. I noticed you're heavily investing in cloud ML infrastructure.",
        timestamp: '2026-02-20T09:00:00Z',
        status: 'read',
      },
      {
        id: 'm6',
        sender: 'contact',
        content: "Thanks for reaching out! Yes, we're scaling our AI capabilities significantly. Are you looking to partner or collaborate?",
        timestamp: '2026-02-20T10:30:00Z',
      },
      {
        id: 'm7',
        sender: 'user',
        content: 'We specialize in scalable ML infrastructure and distributed computing. We can help accelerate model training across your Azure ecosystem by 40%.',
        timestamp: '2026-02-20T11:00:00Z',
        status: 'read',
      },
      {
        id: 'm8',
        sender: 'contact',
        content: 'That sounds impressive. Model training optimization is one of our key focus areas. Can you share some technical details?',
        timestamp: '2026-02-20T14:15:00Z',
      },
      {
        id: 'm9',
        sender: 'user',
        content: 'Absolutely! I can schedule a technical deep dive. We have case studies from enterprise clients showing 40% improvement in training speed and 25% cost reduction.',
        timestamp: '2026-02-20T15:00:00Z',
        status: 'read',
      },
      {
        id: 'm10',
        sender: 'contact',
        content: 'Sounds great! Let me coordinate with the Azure team.',
        timestamp: '2026-02-20T16:45:00Z',
      },
    ],
  },
  {
    id: 'c3',
    company_name: 'Stripe',
    company_id: '3',
    last_message: "We'll evaluate and get back to you by end of week.",
    last_message_time: '2026-02-19T17:30:00Z',
    unread_count: 1,
    messages: [
      {
        id: 'm11',
        sender: 'user',
        content: "Hi, I saw Stripe is expanding the payments infrastructure team. We work on backend performance optimization for fintech companies.",
        timestamp: '2026-02-19T10:00:00Z',
        status: 'read',
      },
      {
        id: 'm12',
        sender: 'contact',
        content: "Thanks for the message! Yes, we're always looking to optimize our payment processing pipeline. What's your specialty?",
        timestamp: '2026-02-19T11:20:00Z',
      },
      {
        id: 'm13',
        sender: 'user',
        content: 'We reduce payment transaction latency and improve throughput. Our solutions have helped fintech platforms process 10x more transactions with the same infrastructure.',
        timestamp: '2026-02-19T12:00:00Z',
        status: 'read',
      },
      {
        id: 'm14',
        sender: 'contact',
        content: 'That is very relevant. Reducing latency is critical for our global payment operations. Tell me more about your approach.',
        timestamp: '2026-02-19T14:45:00Z',
      },
      {
        id: 'm15',
        sender: 'user',
        content: 'We combine edge computing, intelligent caching, and database optimization. Happy to walk through a technical architecture review.',
        timestamp: '2026-02-19T15:30:00Z',
        status: 'read',
      },
      {
        id: 'm16',
        sender: 'contact',
        content: "We'll evaluate and get back to you by end of week.",
        timestamp: '2026-02-19T17:30:00Z',
      },
    ],
  },
]

// Mock Company Analytics
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const mockCompanyAnalytics: Record<string, any> = {
  '1': {
    company: {
      id: '1',
      name: 'Tesla Inc.',
      industry: 'Automotive & Clean Energy',
      location: 'Palo Alto, CA',
      founded_year: 2003,
      employee_count: '127,000+',
      revenue: '$81.46B (2023)',
      intent_score: 92,
      confidence_score: 88,
    },
    intentVisualization: {
      intent_score: 92,
      confidence_score: 88,
      score_label: 'Very High Intent',
    },
    signalBreakdown: [
      { name: 'Hiring Signals', value: 95, max: 100 },
      { name: 'LinkedIn Activity', value: 88, max: 100 },
      { name: 'Engagement Score', value: 76, max: 100 },
      { name: 'News Activity', value: 92, max: 100 },
    ],
    strategyInsights: {
      recommended_channel: 'LinkedIn',
      recommended_timing: 'Morning (9-11 AM PST)',
      recommended_tone: 'Professional & Technical',
      ai_reasoning: 'Based on recent hiring signals and LinkedIn activity, Tesla is actively expanding their AI team. The company shows high engagement with technical content during morning hours. A professional approach highlighting specific technical contributions will resonate best.',
    },
    engagementTrend: [
      { date: '2026-01-15', engagement: 45, intent: 70 },
      { date: '2026-01-22', engagement: 52, intent: 75 },
      { date: '2026-01-29', engagement: 61, intent: 78 },
      { date: '2026-02-05', engagement: 68, intent: 82 },
      { date: '2026-02-12', engagement: 77, intent: 88 },
      { date: '2026-02-19', engagement: 83, intent: 92 },
    ],
  },
  '2': {
    company: {
      id: '2',
      name: 'Microsoft',
      industry: 'Technology & Cloud Computing',
      location: 'Redmond, WA',
      founded_year: 1975,
      employee_count: '221,000+',
      revenue: '$198.27B (2023)',
      intent_score: 87,
      confidence_score: 91,
    },
    intentVisualization: {
      intent_score: 87,
      confidence_score: 91,
      score_label: 'High Intent',
    },
    signalBreakdown: [
      { name: 'Hiring Signals', value: 90, max: 100 },
      { name: 'LinkedIn Activity', value: 85, max: 100 },
      { name: 'Engagement Score', value: 82, max: 100 },
      { name: 'News Activity', value: 87, max: 100 },
    ],
    strategyInsights: {
      recommended_channel: 'Email',
      recommended_timing: 'Morning (8-10 AM EST)',
      recommended_tone: 'Professional & Enterprise-focused',
      ai_reasoning: 'Microsoft is actively expanding its AI capabilities across teams. Email outreach highlighting Azure integration and enterprise-scale solutions shows strong resonance. Focus on ROI and scalability for enterprise environments.',
    },
    engagementTrend: [
      { date: '2026-01-15', engagement: 48, intent: 68 },
      { date: '2026-01-22', engagement: 55, intent: 73 },
      { date: '2026-01-29', engagement: 62, intent: 78 },
      { date: '2026-02-05', engagement: 70, intent: 82 },
      { date: '2026-02-12', engagement: 78, intent: 86 },
      { date: '2026-02-19', engagement: 85, intent: 87 },
    ],
  },
  '3': {
    company: {
      id: '3',
      name: 'Stripe',
      industry: 'Financial Technology & Payments',
      location: 'San Francisco, CA',
      founded_year: 2010,
      employee_count: '14,000+',
      revenue: 'Estimated $20B+ ARR',
      intent_score: 78,
      confidence_score: 82,
    },
    intentVisualization: {
      intent_score: 78,
      confidence_score: 82,
      score_label: 'High Intent',
    },
    signalBreakdown: [
      { name: 'Hiring Signals', value: 85, max: 100 },
      { name: 'LinkedIn Activity', value: 80, max: 100 },
      { name: 'Engagement Score', value: 75, max: 100 },
      { name: 'News Activity', value: 78, max: 100 },
    ],
    strategyInsights: {
      recommended_channel: 'LinkedIn',
      recommended_timing: 'Midweek (Tuesday-Thursday), 10 AM-12 PM PT',
      recommended_tone: 'Technical & Product-focused',
      ai_reasoning: 'Stripe engineering teams are highly engaged with technical content on LinkedIn. They respond well to concrete examples and performance metrics. Highlight payment processing efficiency, transaction speed, and API reliability.',
    },
    engagementTrend: [
      { date: '2026-01-15', engagement: 41, intent: 60 },
      { date: '2026-01-22', engagement: 48, intent: 65 },
      { date: '2026-01-29', engagement: 55, intent: 70 },
      { date: '2026-02-05', engagement: 65, intent: 74 },
      { date: '2026-02-12', engagement: 72, intent: 77 },
      { date: '2026-02-19', engagement: 79, intent: 78 },
    ],
  },
}

// Mock Company News
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const mockCompanyNews: Record<string, any[]> = {
  '1': [
    {
      id: 'n1',
      headline: 'Tesla Announces $100M Investment in AI Research Lab',
      source: 'TechCrunch',
      date: '2026-02-18',
      sentiment: 'positive',
      url: 'https://techcrunch.com/tesla-ai-lab',
    },
    {
      id: 'n2',
      headline: 'Tesla Expands Autopilot Team with 50 New Hires',
      source: 'Bloomberg',
      date: '2026-02-15',
      sentiment: 'positive',
      url: 'https://bloomberg.com/tesla-hiring',
    },
    {
      id: 'n3',
      headline: 'Elon Musk Discusses Future of AI at Tesla',
      source: 'Reuters',
      date: '2026-02-10',
      sentiment: 'neutral',
      url: 'https://reuters.com/musk-ai',
    },
    {
      id: 'n4',
      headline: 'Tesla AI Day 2026: Major Announcements Expected',
      source: 'The Verge',
      date: '2026-02-05',
      sentiment: 'positive',
      url: 'https://theverge.com/tesla-ai-day',
    },
  ],
  '2': [
    {
      id: 'n8',
      headline: 'Microsoft Opens New AI Research Lab in Seattle',
      source: 'TechCrunch',
      date: '2026-02-19',
      sentiment: 'positive',
      url: 'https://techcrunch.com/microsoft-ai-lab',
    },
    {
      id: 'n9',
      headline: 'Microsoft Copilot Integration Expands Across Azure',
      source: 'Microsoft Blog',
      date: '2026-02-17',
      sentiment: 'positive',
      url: 'https://microsoft.com/copilot-azure',
    },
    {
      id: 'n10',
      headline: 'Satya Nadella Announces $10B AI Investment Plan',
      source: 'Bloomberg',
      date: '2026-02-14',
      sentiment: 'positive',
      url: 'https://bloomberg.com/nadella-ai-investment',
    },
    {
      id: 'n11',
      headline: 'Microsoft Hiring 5000+ AI Engineers for Cloud Division',
      source: 'LinkedIn News',
      date: '2026-02-12',
      sentiment: 'positive',
      url: 'https://linkedin.com/news/microsoft-hiring',
    },
    {
      id: 'n12',
      headline: 'Microsoft Partners with Leading Universities on AI Research',
      source: 'MIT News',
      date: '2026-02-08',
      sentiment: 'neutral',
      url: 'https://mitnews.com/microsoft-partnership',
    },
  ],
  '3': [
    {
      id: 'n13',
      headline: 'Stripe Expands Backend Infrastructure with $2B Investment',
      source: 'VentureBeat',
      date: '2026-02-20',
      sentiment: 'positive',
      url: 'https://venturebeat.com/stripe-infrastructure',
    },
    {
      id: 'n14',
      headline: 'Stripe Launches New Payment AI Features',
      source: 'The Block',
      date: '2026-02-18',
      sentiment: 'positive',
      url: 'https://theblock.com/stripe-ai-payments',
    },
    {
      id: 'n15',
      headline: 'Stripe Hiring 2000+ Engineers for Payments Team',
      source: 'LinkedIn Jobs',
      date: '2026-02-15',
      sentiment: 'positive',
      url: 'https://linkedin.com/jobs/stripe',
    },
    {
      id: 'n16',
      headline: 'Stripe Achieves $65B Valuation in Latest Funding Round',
      source: 'Forbes',
      date: '2026-02-10',
      sentiment: 'positive',
      url: 'https://forbes.com/stripe-funding',
    },
    {
      id: 'n17',
      headline: 'Stripe Announces New Global Expansion Initiative',
      source: 'Financial Times',
      date: '2026-02-06',
      sentiment: 'neutral',
      url: 'https://ft.com/stripe-expansion',
    },
  ],
}

// Mock Search Results
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const mockSearchResults: Record<string, any[]> = {
  tesla: [
    { id: '1', name: 'Tesla Inc.', industry: 'Automotive', intent_score: 92, location: 'Palo Alto, CA' },
  ],
  openai: [
    { id: '2', name: 'OpenAI', industry: 'Artificial Intelligence', intent_score: 85, location: 'San Francisco, CA' },
  ],
  stripe: [
    { id: '3', name: 'Stripe', industry: 'Financial Technology', intent_score: 78, location: 'San Francisco, CA' },
  ],
  tech: [
    { id: '1', name: 'Tesla Inc.', industry: 'Automotive', intent_score: 92, location: 'Palo Alto, CA' },
    { id: '2', name: 'OpenAI', industry: 'Artificial Intelligence', intent_score: 85, location: 'San Francisco, CA' },
    { id: '3', name: 'Stripe', industry: 'Financial Technology', intent_score: 78, location: 'San Francisco, CA' },
  ],
}

// Mock Buyers for Outreach Visualization
export const mockBuyers: Buyer[] = [
  { id: 'BUY_57096', name: 'Buyer 57096', industry: 'Chemicals' },
  { id: 'BUY_18472', name: 'Buyer 18472', industry: 'Software' },
  { id: 'BUY_86677', name: 'Buyer 86677', industry: 'Finance' },
  { id: 'BUY_43385', name: 'Buyer 43385', industry: 'Retail' },
  { id: 'BUY_36015', name: 'Buyer 36015', industry: 'Education' },
  { id: 'BUY_59504', name: 'Buyer 59504', industry: 'Healthcare' },
  { id: 'BUY_73568', name: 'Buyer 73568', industry: 'Construction' },
  { id: 'BUY_35716', name: 'Buyer 35716', industry: 'Energy' },
  { id: 'BUY_70104', name: 'Buyer 70104', industry: 'Telecom' },
  { id: 'BUY_21806', name: 'Buyer 21806', industry: 'Automotive' },
  { id: 'BUY_18677', name: 'Buyer 18677', industry: 'Food & Beverage' },
  { id: 'BUY_68002', name: 'Buyer 68002', industry: 'Logistics' },
  { id: 'BUY_68164', name: 'Buyer 68164', industry: 'Pharma' },
  { id: 'BUY_99543', name: 'Buyer 99543', industry: 'Technology' },
  { id: 'BUY_64874', name: 'Buyer 64874', industry: 'Aerospace' },
  { id: 'BUY_36727', name: 'Buyer 36727', industry: 'Hospitality' },
  { id: 'BUY_98156', name: 'Buyer 98156', industry: 'Apparel' },
  { id: 'BUY_23878', name: 'Buyer 23878', industry: 'Legal' },
  { id: 'BUY_77508', name: 'Buyer 77508', industry: 'Media' },
  { id: 'BUY_72750', name: 'Buyer 72750', industry: 'Public Sector' },
  { id: 'BUY_77149', name: 'Buyer 77149', industry: 'Mining' },
  { id: 'BUY_42262', name: 'Buyer 42262', industry: 'Real Estate' },
  { id: 'BUY_78426', name: 'Buyer 78426', industry: 'Travel' },
  { id: 'BUY_77709', name: 'Buyer 77709', industry: 'Wholesale' },
]

export const mockBuyerOutreachData: Record<string, BuyerOutreachData> = {
  'BUY_57096': {
    buyer_id: 'BUY_57096',
    intent_score: 92,
    linkedin_engagement: 0.94,
    groups: 'Global MSME Alliance',
    previous_channel: 'Email',
    channels: [
      { name: 'Email', value: 95, color: '#ea4335' },
      { name: 'LinkedIn', value: 94, color: '#0077b5' },
    ],
  },
  'BUY_18472': {
    buyer_id: 'BUY_18472',
    intent_score: 85,
    linkedin_engagement: 0.67,
    previous_channel: 'Email',
    channels: [
      { name: 'Email', value: 86, color: '#ea4335' },
      { name: 'LinkedIn', value: 67, color: '#0077b5' },
    ],
  },
  'BUY_86677': {
    buyer_id: 'BUY_86677',
    intent_score: 75,
    linkedin_engagement: 0.59,
    previous_channel: 'LinkedIn',
    channels: [
      { name: 'LinkedIn', value: 59, color: '#0077b5' },
      { name: 'Email', value: 45, color: '#ea4335' },
    ],
  },
  'BUY_43385': {
    buyer_id: 'BUY_43385',
    intent_score: 82,
    linkedin_engagement: 0.69,
    previous_channel: 'SMS',
    channels: [
      { name: 'SMS', value: 88, color: '#10b981' },
      { name: 'LinkedIn', value: 69, color: '#0077b5' },
    ],
  },
  'BUY_36015': {
    buyer_id: 'BUY_36015',
    intent_score: 95,
    linkedin_engagement: 0.27,
    previous_channel: 'WhatsApp',
    channels: [
      { name: 'WhatsApp', value: 95, color: '#25D366' },
      { name: 'Email', value: 27, color: '#ea4335' },
    ],
  },
  'BUY_59504': {
    buyer_id: 'BUY_59504',
    intent_score: 88,
    linkedin_engagement: 0.73,
    previous_channel: 'Call',
    channels: [
      { name: 'Call', value: 93, color: '#3b82f6' },
      { name: 'Email', value: 73, color: '#ea4335' },
    ],
  },
  'BUY_73568': {
    buyer_id: 'BUY_73568',
    intent_score: 56,
    linkedin_engagement: 0.43,
    previous_channel: 'Email',
    channels: [
      { name: 'Email', value: 56, color: '#ea4335' },
      { name: 'LinkedIn', value: 43, color: '#0077b5' },
    ],
  },
  'BUY_35716': {
    buyer_id: 'BUY_35716',
    intent_score: 71,
    linkedin_engagement: 0.49,
    previous_channel: 'WhatsApp',
    channels: [
      { name: 'WhatsApp', value: 71, color: '#25D366' },
      { name: 'Email', value: 49, color: '#ea4335' },
    ],
  },
  'BUY_70104': {
    buyer_id: 'BUY_70104',
    intent_score: 99,
    linkedin_engagement: 0.37,
    previous_channel: 'WhatsApp',
    channels: [
      { name: 'WhatsApp', value: 99, color: '#25D366' },
      { name: 'LinkedIn', value: 37, color: '#0077b5' },
    ],
  },
  'BUY_21806': {
    buyer_id: 'BUY_21806',
    intent_score: 89,
    linkedin_engagement: 0.31,
    previous_channel: 'Email',
    channels: [
      { name: 'Email', value: 89, color: '#ea4335' },
      { name: 'LinkedIn', value: 31, color: '#0077b5' },
    ],
  },
  'BUY_18677': {
    buyer_id: 'BUY_18677',
    intent_score: 83,
    linkedin_engagement: 0.54,
    previous_channel: 'LinkedIn',
    channels: [
      { name: 'LinkedIn', value: 83, color: '#0077b5' },
      { name: 'WhatsApp', value: 54, color: '#25D366' },
    ],
  },
  'BUY_68002': {
    buyer_id: 'BUY_68002',
    intent_score: 88,
    linkedin_engagement: 0.83,
    previous_channel: 'LinkedIn',
    channels: [
      { name: 'LinkedIn', value: 88, color: '#0077b5' },
      { name: 'Call', value: 83, color: '#3b82f6' },
    ],
  },
  'BUY_68164': {
    buyer_id: 'BUY_68164',
    intent_score: 84,
    linkedin_engagement: 0.72,
    previous_channel: 'LinkedIn',
    channels: [
      { name: 'LinkedIn', value: 84, color: '#0077b5' },
      { name: 'Call', value: 72, color: '#3b82f6' },
    ],
  },
  'BUY_99543': {
    buyer_id: 'BUY_99543',
    intent_score: 58,
    linkedin_engagement: 0.43,
    previous_channel: 'Call',
    channels: [
      { name: 'Call', value: 58, color: '#3b82f6' },
      { name: 'LinkedIn', value: 43, color: '#0077b5' },
    ],
  },
  'BUY_64874': {
    buyer_id: 'BUY_64874',
    intent_score: 45,
    linkedin_engagement: 0.36,
    previous_channel: 'LinkedIn',
    channels: [
      { name: 'LinkedIn', value: 45, color: '#0077b5' },
      { name: 'Email', value: 36, color: '#ea4335' },
    ],
  },
  'BUY_36727': {
    buyer_id: 'BUY_36727',
    intent_score: 66,
    linkedin_engagement: 0.45,
    previous_channel: 'WhatsApp',
    channels: [
      { name: 'WhatsApp', value: 66, color: '#25D366' },
      { name: 'LinkedIn', value: 45, color: '#0077b5' },
    ],
  },
  'BUY_98156': {
    buyer_id: 'BUY_98156',
    intent_score: 86,
    linkedin_engagement: 0.72,
    previous_channel: 'LinkedIn',
    channels: [
      { name: 'LinkedIn', value: 86, color: '#0077b5' },
      { name: 'Call', value: 72, color: '#3b82f6' },
    ],
  },
  'BUY_23878': {
    buyer_id: 'BUY_23878',
    intent_score: 99,
    linkedin_engagement: 0.87,
    previous_channel: 'Email',
    channels: [
      { name: 'Email', value: 99, color: '#ea4335' },
      { name: 'LinkedIn', value: 87, color: '#0077b5' },
    ],
  },
  'BUY_77508': {
    buyer_id: 'BUY_77508',
    intent_score: 61,
    linkedin_engagement: 0.39,
    previous_channel: 'LinkedIn',
    channels: [
      { name: 'LinkedIn', value: 61, color: '#0077b5' },
      { name: 'WhatsApp', value: 39, color: '#25D366' },
    ],
  },
  'BUY_72750': {
    buyer_id: 'BUY_72750',
    intent_score: 77,
    linkedin_engagement: 0.69,
    previous_channel: 'Call',
    channels: [
      { name: 'Call', value: 77, color: '#3b82f6' },
      { name: 'LinkedIn', value: 69, color: '#0077b5' },
    ],
  },
  'BUY_77149': {
    buyer_id: 'BUY_77149',
    intent_score: 65,
    linkedin_engagement: 0.50,
    previous_channel: 'WhatsApp',
    channels: [
      { name: 'WhatsApp', value: 65, color: '#25D366' },
      { name: 'LinkedIn', value: 50, color: '#0077b5' },
    ],
  },
  'BUY_42262': {
    buyer_id: 'BUY_42262',
    intent_score: 86,
    linkedin_engagement: 0.58,
    previous_channel: 'Call',
    channels: [
      { name: 'Call', value: 86, color: '#3b82f6' },
      { name: 'SMS', value: 58, color: '#10b981' },
    ],
  },
  'BUY_78426': {
    buyer_id: 'BUY_78426',
    intent_score: 83,
    linkedin_engagement: 0.78,
    previous_channel: 'LinkedIn',
    channels: [
      { name: 'LinkedIn', value: 83, color: '#0077b5' },
      { name: 'WhatsApp', value: 78, color: '#25D366' },
    ],
  },
  'BUY_77709': {
    buyer_id: 'BUY_77709',
    intent_score: 80,
    linkedin_engagement: 0.64,
    previous_channel: 'Email',
    channels: [
      { name: 'Email', value: 80, color: '#ea4335' },
      { name: 'LinkedIn', value: 64, color: '#0077b5' },
    ],
  },
}
