import type {
  Company,
  DashboardStats,
  Signal,
  Workflow,
  Conversation,
  Message,
} from '@/types'

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  total_companies: 1247,
  high_intent_companies: 342,
  medium_intent_companies: 568,
  low_intent_companies: 337,
  intent_distribution: [
    { name: 'High Intent', value: 342, color: '#10b981' },
    { name: 'Medium Intent', value: 568, color: '#f59e0b' },
    { name: 'Low Intent', value: 337, color: '#ef4444' },
  ],
  channel_effectiveness: [
    { channel: 'LinkedIn', effectiveness: 85, count: 450 },
    { channel: 'Email', effectiveness: 72, count: 520 },
    { channel: 'WhatsApp', effectiveness: 68, count: 277 },
  ],
  success_rate_trend: [
    { date: '2026-01-01', rate: 65 },
    { date: '2026-01-08', rate: 68 },
    { date: '2026-01-15', rate: 71 },
    { date: '2026-01-22', rate: 73 },
    { date: '2026-01-29', rate: 75 },
    { date: '2026-02-05', rate: 78 },
    { date: '2026-02-12', rate: 80 },
    { date: '2026-02-19', rate: 82 },
  ],
  recent_companies: [
    {
      id: '1',
      name: 'Tesla Inc.',
      industry: 'Automotive',
      location: 'Austin, TX',
      intent_score: 92,
      hiring_signal: 'Hiring 15 AI Engineers',
      engagement_score: 88,
      recommended_channel: 'LinkedIn',
      confidence_score: 94,
      status: 'Active',
      last_signal: '2 hours ago',
    },
    {
      id: '2',
      name: 'Microsoft',
      industry: 'Technology',
      location: 'Redmond, WA',
      intent_score: 87,
      hiring_signal: 'Opened new AI lab',
      engagement_score: 85,
      recommended_channel: 'Email',
      confidence_score: 91,
      status: 'Active',
      last_signal: '5 hours ago',
    },
    {
      id: '3',
      name: 'Stripe',
      industry: 'FinTech',
      location: 'San Francisco, CA',
      intent_score: 78,
      hiring_signal: 'Hiring Backend Engineers',
      engagement_score: 76,
      recommended_channel: 'LinkedIn',
      confidence_score: 82,
      status: 'Active',
      last_signal: '1 day ago',
    },
  ],
  upcoming_meetings: [
    {
      id: 'm1',
      company_name: 'Tesla Inc.',
      contact_name: 'John Doe',
      time: '2026-02-22T10:00:00Z',
      duration: '45 min',
      type: 'Video',
      status: 'Confirmed',
    },
    {
      id: 'm2',
      company_name: 'Stripe',
      contact_name: 'Sarah Smith',
      time: '2026-02-22T14:30:00Z',
      duration: '30 min',
      type: 'Call',
      status: 'Confirmed',
    },
    {
      id: 'm3',
      company_name: 'Microsoft',
      contact_name: 'Michael Brown',
      time: '2026-02-23T09:00:00Z',
      duration: '60 min',
      type: 'Video',
      status: 'Pending',
    },
  ],
}

// Mock Companies
export const mockCompaniesList: Company[] = [
  {
    id: '1',
    name: 'Tesla Inc.',
    industry: 'Automotive',
    location: 'Austin, TX',
    intent_score: 92,
    hiring_signal: 'Hiring 15 AI Engineers',
    engagement_score: 88,
    recommended_channel: 'LinkedIn',
    confidence_score: 94,
    status: 'Active',
    last_signal: '2 hours ago',
  },
  {
    id: '2',
    name: 'Microsoft',
    industry: 'Technology',
    location: 'Redmond, WA',
    intent_score: 87,
    hiring_signal: 'Opened new AI lab',
    engagement_score: 85,
    recommended_channel: 'Email',
    confidence_score: 91,
    status: 'Active',
    last_signal: '5 hours ago',
  },
  {
    id: '3',
    name: 'Stripe',
    industry: 'FinTech',
    location: 'San Francisco, CA',
    intent_score: 78,
    hiring_signal: 'Hiring Backend Engineers',
    engagement_score: 76,
    recommended_channel: 'LinkedIn',
    confidence_score: 82,
    status: 'Active',
    last_signal: '1 day ago',
  },
  {
    id: '4',
    name: 'Airbnb',
    industry: 'Travel',
    location: 'San Francisco, CA',
    intent_score: 74,
    hiring_signal: 'Expanding team',
    engagement_score: 72,
    recommended_channel: 'Email',
    confidence_score: 78,
    status: 'Active',
    last_signal: '2 days ago',
  },
  {
    id: '5',
    name: 'Uber',
    industry: 'Transportation',
    location: 'San Francisco, CA',
    intent_score: 69,
    hiring_signal: 'Hiring Product Managers',
    engagement_score: 65,
    recommended_channel: 'LinkedIn',
    confidence_score: 73,
    status: 'Active',
    last_signal: '3 days ago',
  },
]

// Mock Company Detail
export const mockCompanyDetail: Company = {
  id: '1',
  name: 'Tesla Inc.',
  industry: 'Automotive',
  location: 'Austin, TX',
  intent_score: 92,
  hiring_signal: 'Hiring 15 AI Engineers',
  engagement_score: 88,
  recommended_channel: 'LinkedIn',
  confidence_score: 94,
  status: 'Active',
  signals: [
    {
      id: 's1',
      type: 'hiring',
      title: 'Hiring 15 AI Engineers',
      description: 'Tesla is actively hiring AI engineers for their autopilot team',
      strength: 95,
      timestamp: '2026-02-21T10:00:00Z',
      source: 'LinkedIn Jobs',
    },
    {
      id: 's2',
      type: 'linkedin',
      title: 'High engagement on AI posts',
      description: 'Company executives showing strong interest in AI content',
      strength: 88,
      timestamp: '2026-02-20T15:30:00Z',
      source: 'LinkedIn Activity',
    },
    {
      id: 's3',
      type: 'news',
      title: 'Announced new AI research initiative',
      description: 'Tesla announced $100M investment in AI research',
      strength: 92,
      timestamp: '2026-02-19T09:00:00Z',
      source: 'TechCrunch',
    },
  ],
  strategy: {
    id: 'str1',
    company_id: '1',
    recommended_channel: 'LinkedIn',
    recommended_timing: 'Tuesday or Wednesday, 9-11 AM',
    recommended_tone: 'Professional, technical, data-driven',
    strategy_explanation:
      'Based on hiring signals and LinkedIn engagement, a direct approach highlighting AI expertise and technical capabilities would be most effective. Focus on concrete achievements and data.',
    confidence_score: 94,
    signal_contributions: [
      { signal_type: 'Hiring Signals', contribution_percentage: 45 },
      { signal_type: 'LinkedIn Activity', contribution_percentage: 30 },
      { signal_type: 'News & Events', contribution_percentage: 25 },
    ],
  },
  content: {
    linkedin_message: "Hi [Name],\n\nI noticed Tesla is expanding its AI engineering team. With our expertise in scalable machine learning infrastructure and autonomous systems, I believe we could add significant value to your autopilot initiatives.\n\nWe've helped similar automotive companies reduce model training time by 60% and improve accuracy by 15%. Would you be open to a brief conversation about your AI infrastructure needs?\n\nBest regards",
    email_message: "Subject: AI Infrastructure Solutions for Tesla's Autopilot Team\n\nDear [Name],\n\nI hope this email finds you well. I'm reaching out because I noticed Tesla's recent announcement about expanding the AI engineering team and investing $100M in AI research.\n\nAt [Your Company], we specialize in building scalable AI infrastructure for autonomous systems. We've recently helped automotive companies:\n- Reduce model training time by 60%\n- Improve inference latency by 40%\n- Scale to process 10M+ data points daily\n\nGiven Tesla's ambitious AI goals, I'd love to explore how we could support your initiatives. Would you be available for a 15-minute call next week?\n\nBest regards,\n[Your Name]",
    whatsapp_message: "Hi [Name] 👋\n\nI saw Tesla is hiring AI engineers! We've built ML infrastructure for autonomous vehicles that cut training time by 60%.\n\nQuick question: Are you open to exploring AI infrastructure solutions? Happy to share some case studies.\n\n[Your Name]",
  },
}

// Mock Signals
export const mockSignals: Signal[] = [
  {
    id: 's1',
    type: 'hiring',
    title: 'Tesla hiring 15 AI Engineers',
    description: 'Tesla is actively recruiting for autopilot team expansion',
    strength: 95,
    timestamp: '2026-02-21T10:00:00Z',
    source: 'LinkedIn Jobs',
  },
  {
    id: 's2',
    type: 'news',
    title: 'Microsoft opened new AI research lab',
    description: 'Microsoft announced a new $50M AI research facility in Seattle',
    strength: 90,
    timestamp: '2026-02-21T08:30:00Z',
    source: 'TechCrunch',
  },
  {
    id: 's3',
    type: 'hiring',
    title: 'Stripe hiring Backend Engineers',
    description: 'Stripe expanding payments infrastructure team',
    strength: 85,
    timestamp: '2026-02-20T16:45:00Z',
    source: 'LinkedIn Jobs',
  },
  {
    id: 's4',
    type: 'linkedin',
    title: 'Airbnb executives engaging with SaaS content',
    description: 'Multiple C-level executives showing interest in enterprise SaaS',
    strength: 78,
    timestamp: '2026-02-20T14:20:00Z',
    source: 'LinkedIn Activity',
  },
]

// Mock Workflow
export const mockWorkflow: Workflow = {
  id: 'wf1',
  company_id: '1',
  status: 'active',
  nodes: [
    {
      id: '1',
      type: 'start',
      label: 'Start',
      status: 'completed',
      position: { x: 250, y: 50 },
      data: { label: 'Start Workflow' },
    },
    {
      id: '2',
      type: 'action',
      label: 'Visit Profile',
      status: 'completed',
      position: { x: 250, y: 150 },
      data: { label: 'Visit LinkedIn Profile', timing: 'Day 1' },
    },
    {
      id: '3',
      type: 'action',
      label: 'Send Connection',
      status: 'completed',
      position: { x: 250, y: 250 },
      data: { label: 'Send Connection Request', timing: 'Day 1' },
    },
    {
      id: '4',
      type: 'decision',
      label: 'Accepted?',
      status: 'active',
      position: { x: 250, y: 350 },
      data: { label: 'Connection Accepted?' },
    },
    {
      id: '5',
      type: 'action',
      label: 'Send Message',
      status: 'pending',
      position: { x: 100, y: 450 },
      data: { label: 'Send LinkedIn Message', timing: 'Day 3' },
    },
    {
      id: '6',
      type: 'action',
      label: 'Send Email',
      status: 'pending',
      position: { x: 400, y: 450 },
      data: { label: 'Send Cold Email', timing: 'Day 2' },
    },
    {
      id: '7',
      type: 'action',
      label: 'Follow Up',
      status: 'pending',
      position: { x: 250, y: 550 },
      data: { label: 'Follow Up Message', timing: 'Day 7' },
    },
    {
      id: '8',
      type: 'end',
      label: 'End',
      status: 'pending',
      position: { x: 250, y: 650 },
      data: { label: 'Complete Workflow' },
    },
  ],
  edges: [
    { id: 'e1-2', source: '1', target: '2' },
    { id: 'e2-3', source: '2', target: '3' },
    { id: 'e3-4', source: '3', target: '4' },
    { id: 'e4-5', source: '4', target: '5', animated: true },
    { id: 'e4-6', source: '4', target: '6' },
    { id: 'e5-7', source: '5', target: '7' },
    { id: 'e6-7', source: '6', target: '7' },
    { id: 'e7-8', source: '7', target: '8' },
  ],
}

// Mock Conversations
export const mockConversations: Conversation[] = [
  {
    id: 'c1',
    company_name: 'Tesla Inc.',
    company_id: '1',
    last_message: 'That sounds great! Let me check with my team.',
    last_message_time: '2026-02-21T11:30:00Z',
    unread_count: 2,
    messages: [
      {
        id: 'm1',
        sender: 'user',
        content: "Hi! I noticed you're hiring AI engineers. Would love to discuss how we can help.",
        timestamp: '2026-02-21T10:00:00Z',
        status: 'read',
      },
      {
        id: 'm2',
        sender: 'contact',
        content: "Thanks for reaching out! Yes, we're expanding our team. What solutions do you offer?",
        timestamp: '2026-02-21T10:15:00Z',
      },
      {
        id: 'm3',
        sender: 'user',
        content: 'We provide ML infrastructure that can reduce training time by 60%. Can we schedule a demo?',
        timestamp: '2026-02-21T10:30:00Z',
        status: 'read',
      },
      {
        id: 'm4',
        sender: 'contact',
        content: 'That sounds great! Let me check with my team.',
        timestamp: '2026-02-21T11:30:00Z',
      },
    ],
  },
  {
    id: 'c2',
    company_name: 'Microsoft',
    company_id: '2',
    last_message: 'Sure, how about next Tuesday?',
    last_message_time: '2026-02-20T15:45:00Z',
    unread_count: 1,
    messages: [
      {
        id: 'm5',
        sender: 'user',
        content: "Congrats on the new AI lab! Would you be interested in collaboration opportunities?",
        timestamp: '2026-02-20T14:00:00Z',
        status: 'read',
      },
      {
        id: 'm6',
        sender: 'contact',
        content: 'Sure, how about next Tuesday?',
        timestamp: '2026-02-20T15:45:00Z',
      },
    ],
  },
  {
    id: 'c3',
    company_name: 'Stripe',
    company_id: '3',
    last_message: "Thanks, I'll review and get back to you.",
    last_message_time: '2026-02-19T16:20:00Z',
    unread_count: 0,
    messages: [
      {
        id: 'm7',
        sender: 'user',
        content: "Hi, saw you're expanding your payments infrastructure. We specialize in scalable backend systems.",
        timestamp: '2026-02-19T15:00:00Z',
        status: 'read',
      },
      {
        id: 'm8',
        sender: 'contact',
        content: "Thanks, I'll review and get back to you.",
        timestamp: '2026-02-19T16:20:00Z',
      },
    ],
  },
]

// Mock Company Analytics
export const mockCompanyAnalytics: Record<string, any> = {
  '1': {
    company: {
      id: '1',
      name: 'Tesla Inc.',
      industry: 'Automotive & Clean Energy',
      location: 'Palo Alto, CA',
      founded_year: 2003,
      employee_count: '127,000+',
      revenue: '$81.46B (2023)',
      intent_score: 92,
      confidence_score: 88,
    },
    intentVisualization: {
      intent_score: 92,
      confidence_score: 88,
      score_label: 'Very High Intent',
    },
    signalBreakdown: [
      { name: 'Hiring Signals', value: 95, max: 100 },
      { name: 'LinkedIn Activity', value: 88, max: 100 },
      { name: 'Engagement Score', value: 76, max: 100 },
      { name: 'News Activity', value: 92, max: 100 },
    ],
    strategyInsights: {
      recommended_channel: 'LinkedIn',
      recommended_timing: 'Morning (9-11 AM PST)',
      recommended_tone: 'Professional & Technical',
      ai_reasoning: 'Based on recent hiring signals and LinkedIn activity, Tesla is actively expanding their AI team. The company shows high engagement with technical content during morning hours. A professional approach highlighting specific technical contributions will resonate best.',
    },
    engagementTrend: [
      { date: '2026-01-15', engagement: 45, intent: 70 },
      { date: '2026-01-22', engagement: 52, intent: 75 },
      { date: '2026-01-29', engagement: 61, intent: 78 },
      { date: '2026-02-05', engagement: 68, intent: 82 },
      { date: '2026-02-12', engagement: 77, intent: 88 },
      { date: '2026-02-19', engagement: 83, intent: 92 },
    ],
  },
  '2': {
    company: {
      id: '2',
      name: 'OpenAI',
      industry: 'Artificial Intelligence',
      location: 'San Francisco, CA',
      founded_year: 2015,
      employee_count: '1,000+',
      revenue: 'Private',
      intent_score: 85,
      confidence_score: 82,
    },
    intentVisualization: {
      intent_score: 85,
      confidence_score: 82,
      score_label: 'High Intent',
    },
    signalBreakdown: [
      { name: 'Hiring Signals', value: 88, max: 100 },
      { name: 'LinkedIn Activity', value: 92, max: 100 },
      { name: 'Engagement Score', value: 79, max: 100 },
      { name: 'News Activity', value: 85, max: 100 },
    ],
    strategyInsights: {
      recommended_channel: 'Email',
      recommended_timing: 'Afternoon (2-4 PM PST)',
      recommended_tone: 'Innovative & Forward-thinking',
      ai_reasoning: 'OpenAI values innovation and cutting-edge solutions. Email outreach with detailed technical proposals during afternoon hours shows best response rates. Emphasize novel approaches and research-backed methodologies.',
    },
    engagementTrend: [
      { date: '2026-01-15', engagement: 52, intent: 72 },
      { date: '2026-01-22', engagement: 58, intent: 75 },
      { date: '2026-01-29', engagement: 64, intent: 78 },
      { date: '2026-02-05', engagement: 70, intent: 81 },
      { date: '2026-02-12', engagement: 74, intent: 83 },
      { date: '2026-02-19', engagement: 79, intent: 85 },
    ],
  },
}

// Mock Company News
export const mockCompanyNews: Record<string, any[]> = {
  '1': [
    {
      id: 'n1',
      headline: 'Tesla Announces $100M Investment in AI Research Lab',
      source: 'TechCrunch',
      date: '2026-02-18',
      sentiment: 'positive',
      url: 'https://techcrunch.com/tesla-ai-lab',
    },
    {
      id: 'n2',
      headline: 'Tesla Expands Autopilot Team with 50 New Hires',
      source: 'Bloomberg',
      date: '2026-02-15',
      sentiment: 'positive',
      url: 'https://bloomberg.com/tesla-hiring',
    },
    {
      id: 'n3',
      headline: 'Elon Musk Discusses Future of AI at Tesla',
      source: 'Reuters',
      date: '2026-02-10',
      sentiment: 'neutral',
      url: 'https://reuters.com/musk-ai',
    },
    {
      id: 'n4',
      headline: 'Tesla AI Day 2026: Major Announcements Expected',
      source: 'The Verge',
      date: '2026-02-05',
      sentiment: 'positive',
      url: 'https://theverge.com/tesla-ai-day',
    },
  ],
  '2': [
    {
      id: 'n5',
      headline: 'OpenAI Launches GPT-5 with Revolutionary Capabilities',
      source: 'MIT Technology Review',
      date: '2026-02-17',
      sentiment: 'positive',
      url: 'https://technologyreview.com/openai-gpt5',
    },
    {
      id: 'n6',
      headline: 'OpenAI Partners with Major Healthcare Providers',
      source: 'Healthcare IT News',
      date: '2026-02-12',
      sentiment: 'positive',
      url: 'https://healthcareitnews.com/openai',
    },
    {
      id: 'n7',
      headline: 'Sam Altman Discusses AI Safety Measures',
      source: 'CNBC',
      date: '2026-02-08',
      sentiment: 'neutral',
      url: 'https://cnbc.com/altman-ai-safety',
    },
  ],
}

// Mock Search Results
export const mockSearchResults: Record<string, any[]> = {
  tesla: [
    { id: '1', name: 'Tesla Inc.', industry: 'Automotive', intent_score: 92, location: 'Palo Alto, CA' },
  ],
  openai: [
    { id: '2', name: 'OpenAI', industry: 'Artificial Intelligence', intent_score: 85, location: 'San Francisco, CA' },
  ],
  stripe: [
    { id: '3', name: 'Stripe', industry: 'Financial Technology', intent_score: 78, location: 'San Francisco, CA' },
  ],
  tech: [
    { id: '1', name: 'Tesla Inc.', industry: 'Automotive', intent_score: 92, location: 'Palo Alto, CA' },
    { id: '2', name: 'OpenAI', industry: 'Artificial Intelligence', intent_score: 85, location: 'San Francisco, CA' },
    { id: '3', name: 'Stripe', industry: 'Financial Technology', intent_score: 78, location: 'San Francisco, CA' },
  ],
}
